const usernames = [
  "Aaran",
  "Aaren",
  "Aarez",
  "Aarman",
  "Aaron",
  "Aaron-James",
  "Aarron",
  "Aaryan",
  "Aaryn",
  "Aayan",
  "Aazaan",
  "Abaan",
  "Abbas",
  "Abdallah",
  "Abdalroof",
  "Abdihakim",
  "Abdirahman",
  "Abdisalam",
  "Abdul",
  "Abdul-Aziz",
  "Abdulbasir",
  "Abdulkadir",
  "Abdulkarem",
  "Smith",
  "Jones",
  "Coollastname",
  "enter_name_here",
  "Ze",
  "Zechariah",
  "Zeek",
  "Zeeshan",
  "Zeid",
  "Zein",
  "Zen",
  "Zendel",
  "Zenith",
  "Zennon",
  "Zeph",
  "Zerah",
  "Zhen",
  "Zhi",
  "Zhong",
  "Zhuo",
  "Zi",
  "Zidane",
  "Zijie",
  "Zinedine",
  "Zion",
  "Zishan",
  "Ziya",
  "Ziyaan",
  "Zohaib",
  "Zohair",
  "Zoubaeir",
  "Zubair",
  "Zubayr",
  "Zuriel",
  "Xander",
  "Jared",
  "Courtney",
  "Gillian",
  "Clark",
  "Jared",
  "Grace",
  "Kelsey",
  "Tamar",
  "Alex",
  "Mark",
  "Tamar",
  "Farish",
  "Sarah",
  "Nathaniel",
  "Parker",
];
const emails = [
  "lucile66@yahoo.com",
  "frida.koch@hotmail.com",
  "eldora_veum7@hotmail.com",
  "tremayne.jenkins@yahoo.com",
  "buster.watsica@hotmail.com",
  "else82@hotmail.com",
  "lucius_hilll@gmail.com",
  "bettie30@yahoo.com",
  "linda_thiel24@hotmail.com",
  "mauricio10@gmail.com",
  "orrin_wyman@gmail.com",
  "jonathon.pfeffer51@hotmail.com",
  "marcel.collier91@yahoo.com",
  "kamille_lowe@hotmail.com",
  "krystal.kling62@hotmail.com",
  "dina.jacobi@hotmail.com",
  "mack_oconnell7@hotmail.com",
  "leila.krajcik62@gmail.com",
  "maymie83@yahoo.com",
  "candace_yost@yahoo.com",
];

const genRandomIndex = (arr) => Math.floor(Math.random() * arr.length);

console.log(genRandomIndex(usernames));

const getRandomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

const getRandomUserName = () =>
  `${getRandomArrItem(usernames)}`;

const getRandomEmail = () =>
  `${getRandomArrItem(emails)}`;

  module.exports = {
    getRandomUserName,
    getRandomEmail,
    genRandomIndex,
  }